// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC82LyQf3CSokJj1pnuPo9ij9zKbVxGoao',
    appId: '1:73724529836:android:0ede59947aa790a479e309',
    messagingSenderId: '73724529836',
    projectId: 'harcoapp-af88c',
    storageBucket: 'harcoapp-af88c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLTrh3XP1AIqtRCRg9B5sBKsELYWOndYk',
    appId: '1:73724529836:ios:d526971b1079edef79e309',
    messagingSenderId: '73724529836',
    projectId: 'harcoapp-af88c',
    storageBucket: 'harcoapp-af88c.appspot.com',
    androidClientId: '73724529836-gh5qtph7iubkla51mjn9gq4jfj10j9hg.apps.googleusercontent.com',
    iosClientId: '73724529836-a3cmk67809t9cfad641f5p88820ng7kn.apps.googleusercontent.com',
    iosBundleId: 'com.inersya.harcoappios',
  );
}
